/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Venue = {
  _id: string;
  _type: "venue";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  venueImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  venueName?: string;
  academicBlock?: string;
  locationLink?: string;
  capacity?: number;
};

export type Blog = {
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  date?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Newsletter = {
  _id: string;
  _type: "newsletter";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  link?: string;
  date?: string;
  pdfFile?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    _type: "file";
  };
  coverPhoto?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  isCollab?: boolean;
  clubname?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "club";
  };
  clubnames?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "club";
  }>;
  typeOfEvent?: Array<string>;
  customEventType?: string;
  startDate?: string;
  endDate?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  customVenueOption?: boolean;
  venue?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "venue";
  }>;
  customVenue?: string;
  poster?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  entryFee?: number;
  noOfParticipantsPerTeam?: string;
};

export type Club = {
  _id: string;
  _type: "club";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  abbreviation?: string;
  description?: string;
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  faculty1?: string;
  faculty1url?: string;
  faculty2?: string;
  faculty2url?: string;
  clubType?: "Technical Club" | "Recreational Club" | "Special Team" | "Chapter" | "Literary Club" | "Other";
};

export type Announcement = {
  _id: string;
  _type: "announcement";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  date?: string;
  expiry?: string;
  category?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type OfficeBearer = {
  _id: string;
  _type: "officeBearer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  designation?: string;
  description?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  informalImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type AllSanitySchemaTypes = SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | Geopoint | Slug | Venue | Blog | Newsletter | SanityFileAsset | Event | Club | Announcement | OfficeBearer | SanityImageCrop | SanityImageHotspot | SanityImageAsset | SanityAssetSourceData | SanityImageMetadata;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ../frontend/src/app/about/page.tsx
// Variable: OFFICE_BEARERS_QUERY
// Query: *[  _type == "officeBearer" && designation != "Director"  ]{    _id,    name,    designation,    description,    image,     informalImage,    _type,     _createdAt,     _updatedAt,     _rev   }
export type OFFICE_BEARERS_QUERYResult = Array<{
  _id: string;
  name: string | null;
  designation: string | null;
  description: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  informalImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  _type: "officeBearer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
}>;

// Source: ../frontend/src/app/clubs/page.tsx
// Variable: CLUBS_QUERY
// Query: *[  _type == "club"]{    _id,    name,    logo,    description,    faculty1,    faculty1url,    faculty2,    faculty2url,    clubType}
export type CLUBS_QUERYResult = Array<{
  _id: string;
  name: string | null;
  logo: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  description: string | null;
  faculty1: string | null;
  faculty1url: string | null;
  faculty2: string | null;
  faculty2url: string | null;
  clubType: "Chapter" | "Literary Club" | "Other" | "Recreational Club" | "Special Team" | "Technical Club" | null;
}>;

// Source: ../frontend/src/app/events/page.tsx
// Variable: EVENTS_QUERY
// Query: *[_type == "event"]{    _id,    name,    isCollab,    clubnames[]->{name, abbreviation},    clubname->{name, abbreviation},    typeOfEvent,    customEventType,    description,    poster,    startDate,    endDate,    customVenueOption,    venue[]->{venueName, locationLink},    customVenue,    entryFee,    noOfParticipantsPerTeam  }
export type EVENTS_QUERYResult = Array<{
  _id: string;
  name: string | null;
  isCollab: boolean | null;
  clubnames: Array<{
    name: string | null;
    abbreviation: string | null;
  }> | null;
  clubname: {
    name: string | null;
    abbreviation: string | null;
  } | null;
  typeOfEvent: Array<string> | null;
  customEventType: string | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  poster: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  startDate: string | null;
  endDate: string | null;
  customVenueOption: boolean | null;
  venue: Array<{
    venueName: string | null;
    locationLink: string | null;
  }> | null;
  customVenue: string | null;
  entryFee: number | null;
  noOfParticipantsPerTeam: string | null;
}>;
// Variable: CLUBS_INFO_QUERY
// Query: *[_type == "club"]{    _id,    name,    abbreviation,    clubType  }
export type CLUBS_INFO_QUERYResult = Array<{
  _id: string;
  name: string | null;
  abbreviation: string | null;
  clubType: "Chapter" | "Literary Club" | "Other" | "Recreational Club" | "Special Team" | "Technical Club" | null;
}>;

// Source: ../frontend/src/app/newsletter/page.tsx
// Variable: FETCH_NEWSLETTERS
// Query: *[    _type=="newsletter"  ]{    _id,    link,    date,    pdfFile,    coverPhoto  }
export type FETCH_NEWSLETTERSResult = Array<{
  _id: string;
  link: string | null;
  date: string | null;
  pdfFile: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    _type: "file";
  } | null;
  coverPhoto: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
}>;

// Source: ../frontend/src/components/homepage/announcement.tsx
// Variable: ANNOUNCEMENTS_QUERY
// Query: *[_type == "announcement"]{    _id,    title,    description,    date,    expiry,    category  }
export type ANNOUNCEMENTS_QUERYResult = Array<{
  _id: string;
  title: string | null;
  description: string | null;
  date: string | null;
  expiry: string | null;
  category: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
}>;

// Source: ../frontend/src/components/homepage/office-bearers-&-announcements.tsx
// Variable: ALL_OFFICE_BEARERS_QUERY
// Query: *[  _type == "officeBearer"]{  _id,  name,  designation,  description,  image}
export type ALL_OFFICE_BEARERS_QUERYResult = Array<{
  _id: string;
  name: string | null;
  designation: string | null;
  description: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[\n  _type == \"officeBearer\" && designation != \"Director\"\n  ]{\n    _id,\n    name,\n    designation,\n    description,\n    image, \n    informalImage,\n    _type, \n    _createdAt, \n    _updatedAt, \n    _rev \n  }": OFFICE_BEARERS_QUERYResult;
    "*[\n  _type == \"club\"]{\n    _id,\n    name,\n    logo,\n    description,\n    faculty1,\n    faculty1url,\n    faculty2,\n    faculty2url,\n    clubType}": CLUBS_QUERYResult;
    "\n  *[_type == \"event\"]{\n    _id,\n    name,\n    isCollab,\n    clubnames[]->{name, abbreviation},\n    clubname->{name, abbreviation},\n    typeOfEvent,\n    customEventType,\n    description,\n    poster,\n    startDate,\n    endDate,\n    customVenueOption,\n    venue[]->{venueName, locationLink},\n    customVenue,\n    entryFee,\n    noOfParticipantsPerTeam\n  }\n": EVENTS_QUERYResult;
    "\n  *[_type == \"club\"]{\n    _id,\n    name,\n    abbreviation,\n    clubType\n  }\n": CLUBS_INFO_QUERYResult;
    "*[\n    _type==\"newsletter\"\n  ]{\n    _id,\n    link,\n    date,\n    pdfFile,\n    coverPhoto\n  }": FETCH_NEWSLETTERSResult;
    "*[_type == \"announcement\"]{\n    _id,\n    title,\n    description,\n    date,\n    expiry,\n    category\n  }": ANNOUNCEMENTS_QUERYResult;
    "*[\n  _type == \"officeBearer\"\n]{\n  _id,\n  name,\n  designation,\n  description,\n  image\n}": ALL_OFFICE_BEARERS_QUERYResult;
  }
}
